### ISSUE TITLE
To dos

### ISSUE THREAD

**Issue by MaraAlexeev** [MaraAlexeev/intro_to_R_for_medical_data_rmed2021#11]
Questions:
Is there a way to cite the source of the smoke data? I wasn't clear what the original source was?

Can you two add any citations you want to be included? Any additional acknowledgements?

I have never dealt with licensing issues? Anything to do?

I will make sure things get updated to RStudioCloud and sent to the TAs.

Final to dos: 
[ ] make a copy of the complete workshop rmd and call it teaching_doc.Rmd
[ ] strip out stuff from workshop rmd so participants can't see answers
[ ] render site
[ ] push everything to github
[ ] rebase RstudioCloud project for final version

@laderast @chendaniely

**Comment by laderast** [comment]
The original source is TCGA

**Comment by MaraAlexeev** [comment]
Great! If folks are happy with things, please let me know and I will go through and strip out answers and prep things for the workshop. Will also send out the workspace to TAs tomorrow to get their fresh eyes.

**Comment by chendaniely** [comment]
everything looks good to me!
